version: "3.9"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile-database
    restart: always
    environment:
      MYSQL_USER: scrolls
      MYSQL_PASSWORD: scrolls
      MYSQL_DATABASE: scrolls
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
    volumes:
      - "dbdata:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "./db-healthcheck.sh"]
      start_period: 10s
      retries: 3
      interval: 10s

  scrolls:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      SERVER_IP: localhost
      SERVER_PORT: 8081
      NODE_ID: test-server
      DB_URL: "jdbc:mysql://database:3306/scrolls"
      DB_USER: scrolls
      DB_PASSWORD: scrolls
      CALLERSBANE_URL: ""
    volumes:
      - "scrolls:/scrolls"
    ports:
      - "8081:8081"
      - "8082:8082"

volumes:
  dbdata:
  scrolls: