version: "3.9"
services:
  database:
    image: mariadb:10.10
    restart: always
    environment:
      MYSQL_USER: scrolls
      MYSQL_PASSWORD: scrolls
      MYSQL_DATABASE: scrolls
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
    volumes:
      - "dbdata:/var/lib/mysql"
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "5"

  scrolls:
    image: ghcr.io/wakingstones/turtles:latest
    restart: always
    depends_on:
      - database
    environment:
      SERVER_IP: ${SERVER_IP}
      SERVER_PORT: 8081
      NODE_ID: test-server
      DB_HOST: database
      DB_USER: scrolls
      DB_PASSWORD: scrolls
    volumes:
      - "scrolls:/scrolls/download"
    ports:
      - "8081:8081"
      - "8082:8082"
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "5"

volumes:
  dbdata:
  scrolls: