name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download Callersbane
        run: wget -O callersbane.zip "https://download.scrolls.com/callersbane/server/CallersBane-Server-2.0.1.zip"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Prepare
        run: ./gradlew prepareWorkspace

      - name: Build
        run: ./gradlew build

      - name: Generate archive
        uses: actions/upload-artifact@v1
        with:
          name: Results
          path: build/libs/

      - name: Correct env
        run:
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest
          platforms: linux/amd64,linux/arm64

  deployment:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Demo
    steps:
      - name: Deploy
        run:
          curl -X POST --insecure ${{ secrets.POST_URL }}